/*
Steps:
1) minimize with: https://www.webtoolkitonline.com/sql-minifier.html
2) replace LvLOff with ',_ColName,'
3) replace _WorldId with ',_WorldId,'
4) replace _AllianceId with ',_AllianceId,'
5) replace _OwnAccountId with ',_OwnAccountId,'
*/
SELECT SUM(CASE WHEN ba.LvLOff BETWEEN 0 AND 0.99 THEN 1 ELSE 0 END) AS LvLOff0,
SUM(CASE WHEN ba.LvLOff BETWEEN 1 AND 1.99 THEN 1 ELSE 0 END) AS LvLOff1,
SUM(CASE WHEN ba.LvLOff BETWEEN 2 AND 2.99 THEN 1 ELSE 0 END) AS LvLOff2,
SUM(CASE WHEN ba.LvLOff BETWEEN 3 AND 3.99 THEN 1 ELSE 0 END) AS LvLOff3,
SUM(CASE WHEN ba.LvLOff BETWEEN 4 AND 4.99 THEN 1 ELSE 0 END) AS LvLOff4,
SUM(CASE WHEN ba.LvLOff BETWEEN 5 AND 5.99 THEN 1 ELSE 0 END) AS LvLOff5,
SUM(CASE WHEN ba.LvLOff BETWEEN 6 AND 6.99 THEN 1 ELSE 0 END) AS LvLOff6,
SUM(CASE WHEN ba.LvLOff BETWEEN 7 AND 7.99 THEN 1 ELSE 0 END) AS LvLOff7,
SUM(CASE WHEN ba.LvLOff BETWEEN 8 AND 8.99 THEN 1 ELSE 0 END) AS LvLOff8,
SUM(CASE WHEN ba.LvLOff BETWEEN 9 AND 9.99 THEN 1 ELSE 0 END) AS LvLOff9,
SUM(CASE WHEN ba.LvLOff BETWEEN 10 AND 10.99 THEN 1 ELSE 0 END) AS LvLOff10,
SUM(CASE WHEN ba.LvLOff BETWEEN 11 AND 11.99 THEN 1 ELSE 0 END) AS LvLOff11,
SUM(CASE WHEN ba.LvLOff BETWEEN 12 AND 12.99 THEN 1 ELSE 0 END) AS LvLOff12,
SUM(CASE WHEN ba.LvLOff BETWEEN 13 AND 13.99 THEN 1 ELSE 0 END) AS LvLOff13,
SUM(CASE WHEN ba.LvLOff BETWEEN 14 AND 14.99 THEN 1 ELSE 0 END) AS LvLOff14,
SUM(CASE WHEN ba.LvLOff BETWEEN 15 AND 15.99 THEN 1 ELSE 0 END) AS LvLOff15,
SUM(CASE WHEN ba.LvLOff BETWEEN 16 AND 16.99 THEN 1 ELSE 0 END) AS LvLOff16,
SUM(CASE WHEN ba.LvLOff BETWEEN 17 AND 17.99 THEN 1 ELSE 0 END) AS LvLOff17,
SUM(CASE WHEN ba.LvLOff BETWEEN 18 AND 18.99 THEN 1 ELSE 0 END) AS LvLOff18,
SUM(CASE WHEN ba.LvLOff BETWEEN 19 AND 19.99 THEN 1 ELSE 0 END) AS LvLOff19,
SUM(CASE WHEN ba.LvLOff BETWEEN 20 AND 20.99 THEN 1 ELSE 0 END) AS LvLOff20,
SUM(CASE WHEN ba.LvLOff BETWEEN 21 AND 21.99 THEN 1 ELSE 0 END) AS LvLOff21,
SUM(CASE WHEN ba.LvLOff BETWEEN 22 AND 22.99 THEN 1 ELSE 0 END) AS LvLOff22,
SUM(CASE WHEN ba.LvLOff BETWEEN 23 AND 23.99 THEN 1 ELSE 0 END) AS LvLOff23,
SUM(CASE WHEN ba.LvLOff BETWEEN 24 AND 24.99 THEN 1 ELSE 0 END) AS LvLOff24,
SUM(CASE WHEN ba.LvLOff BETWEEN 25 AND 25.99 THEN 1 ELSE 0 END) AS LvLOff25,
SUM(CASE WHEN ba.LvLOff BETWEEN 26 AND 26.99 THEN 1 ELSE 0 END) AS LvLOff26,
SUM(CASE WHEN ba.LvLOff BETWEEN 27 AND 27.99 THEN 1 ELSE 0 END) AS LvLOff27,
SUM(CASE WHEN ba.LvLOff BETWEEN 28 AND 28.99 THEN 1 ELSE 0 END) AS LvLOff28,
SUM(CASE WHEN ba.LvLOff BETWEEN 29 AND 29.99 THEN 1 ELSE 0 END) AS LvLOff29,
SUM(CASE WHEN ba.LvLOff BETWEEN 30 AND 30.99 THEN 1 ELSE 0 END) AS LvLOff30,
SUM(CASE WHEN ba.LvLOff BETWEEN 31 AND 31.99 THEN 1 ELSE 0 END) AS LvLOff31,
SUM(CASE WHEN ba.LvLOff BETWEEN 32 AND 32.99 THEN 1 ELSE 0 END) AS LvLOff32,
SUM(CASE WHEN ba.LvLOff BETWEEN 33 AND 33.99 THEN 1 ELSE 0 END) AS LvLOff33,
SUM(CASE WHEN ba.LvLOff BETWEEN 34 AND 34.99 THEN 1 ELSE 0 END) AS LvLOff34,
SUM(CASE WHEN ba.LvLOff BETWEEN 35 AND 35.99 THEN 1 ELSE 0 END) AS LvLOff35,
SUM(CASE WHEN ba.LvLOff BETWEEN 36 AND 36.99 THEN 1 ELSE 0 END) AS LvLOff36,
SUM(CASE WHEN ba.LvLOff BETWEEN 37 AND 37.99 THEN 1 ELSE 0 END) AS LvLOff37,
SUM(CASE WHEN ba.LvLOff BETWEEN 38 AND 38.99 THEN 1 ELSE 0 END) AS LvLOff38,
SUM(CASE WHEN ba.LvLOff BETWEEN 39 AND 39.99 THEN 1 ELSE 0 END) AS LvLOff39,
SUM(CASE WHEN ba.LvLOff BETWEEN 40 AND 40.99 THEN 1 ELSE 0 END) AS LvLOff40,
SUM(CASE WHEN ba.LvLOff BETWEEN 41 AND 41.99 THEN 1 ELSE 0 END) AS LvLOff41,
SUM(CASE WHEN ba.LvLOff BETWEEN 42 AND 42.99 THEN 1 ELSE 0 END) AS LvLOff42,
SUM(CASE WHEN ba.LvLOff BETWEEN 43 AND 43.99 THEN 1 ELSE 0 END) AS LvLOff43,
SUM(CASE WHEN ba.LvLOff BETWEEN 44 AND 44.99 THEN 1 ELSE 0 END) AS LvLOff44,
SUM(CASE WHEN ba.LvLOff BETWEEN 45 AND 45.99 THEN 1 ELSE 0 END) AS LvLOff45,
SUM(CASE WHEN ba.LvLOff BETWEEN 46 AND 46.99 THEN 1 ELSE 0 END) AS LvLOff46,
SUM(CASE WHEN ba.LvLOff BETWEEN 47 AND 47.99 THEN 1 ELSE 0 END) AS LvLOff47,
SUM(CASE WHEN ba.LvLOff BETWEEN 48 AND 48.99 THEN 1 ELSE 0 END) AS LvLOff48,
SUM(CASE WHEN ba.LvLOff BETWEEN 49 AND 49.99 THEN 1 ELSE 0 END) AS LvLOff49,
SUM(CASE WHEN ba.LvLOff BETWEEN 50 AND 50.99 THEN 1 ELSE 0 END) AS LvLOff50,
SUM(CASE WHEN ba.LvLOff BETWEEN 51 AND 51.99 THEN 1 ELSE 0 END) AS LvLOff51,
SUM(CASE WHEN ba.LvLOff BETWEEN 52 AND 52.99 THEN 1 ELSE 0 END) AS LvLOff52,
SUM(CASE WHEN ba.LvLOff BETWEEN 53 AND 53.99 THEN 1 ELSE 0 END) AS LvLOff53,
SUM(CASE WHEN ba.LvLOff BETWEEN 54 AND 54.99 THEN 1 ELSE 0 END) AS LvLOff54,
SUM(CASE WHEN ba.LvLOff BETWEEN 55 AND 55.99 THEN 1 ELSE 0 END) AS LvLOff55,
SUM(CASE WHEN ba.LvLOff BETWEEN 56 AND 56.99 THEN 1 ELSE 0 END) AS LvLOff56,
SUM(CASE WHEN ba.LvLOff BETWEEN 57 AND 57.99 THEN 1 ELSE 0 END) AS LvLOff57,
SUM(CASE WHEN ba.LvLOff BETWEEN 58 AND 58.99 THEN 1 ELSE 0 END) AS LvLOff58,
SUM(CASE WHEN ba.LvLOff BETWEEN 59 AND 59.99 THEN 1 ELSE 0 END) AS LvLOff59,
SUM(CASE WHEN ba.LvLOff BETWEEN 60 AND 60.99 THEN 1 ELSE 0 END) AS LvLOff60,
SUM(CASE WHEN ba.LvLOff BETWEEN 61 AND 61.99 THEN 1 ELSE 0 END) AS LvLOff61,
SUM(CASE WHEN ba.LvLOff BETWEEN 62 AND 62.99 THEN 1 ELSE 0 END) AS LvLOff62,
SUM(CASE WHEN ba.LvLOff BETWEEN 63 AND 63.99 THEN 1 ELSE 0 END) AS LvLOff63,
SUM(CASE WHEN ba.LvLOff BETWEEN 64 AND 64.99 THEN 1 ELSE 0 END) AS LvLOff64,
SUM(CASE WHEN ba.LvLOff BETWEEN 65 AND 65.99 THEN 1 ELSE 0 END) AS LvLOff65,
SUM(CASE WHEN ba.LvLOff BETWEEN 66 AND 66.99 THEN 1 ELSE 0 END) AS LvLOff66,
SUM(CASE WHEN ba.LvLOff BETWEEN 67 AND 67.99 THEN 1 ELSE 0 END) AS LvLOff67,
SUM(CASE WHEN ba.LvLOff BETWEEN 68 AND 68.99 THEN 1 ELSE 0 END) AS LvLOff68,
SUM(CASE WHEN ba.LvLOff BETWEEN 69 AND 69.99 THEN 1 ELSE 0 END) AS LvLOff69,
SUM(CASE WHEN ba.LvLOff BETWEEN 70 AND 70.99 THEN 1 ELSE 0 END) AS LvLOff70,
SUM(CASE WHEN ba.LvLOff BETWEEN 71 AND 71.99 THEN 1 ELSE 0 END) AS LvLOff71,
SUM(CASE WHEN ba.LvLOff BETWEEN 72 AND 72.99 THEN 1 ELSE 0 END) AS LvLOff72,
SUM(CASE WHEN ba.LvLOff BETWEEN 73 AND 73.99 THEN 1 ELSE 0 END) AS LvLOff73,
SUM(CASE WHEN ba.LvLOff BETWEEN 74 AND 74.99 THEN 1 ELSE 0 END) AS LvLOff74,
SUM(CASE WHEN ba.LvLOff BETWEEN 75 AND 75.99 THEN 1 ELSE 0 END) AS LvLOff75,
SUM(CASE WHEN ba.LvLOff BETWEEN 76 AND 76.99 THEN 1 ELSE 0 END) AS LvLOff76,
SUM(CASE WHEN ba.LvLOff BETWEEN 77 AND 77.99 THEN 1 ELSE 0 END) AS LvLOff77,
SUM(CASE WHEN ba.LvLOff BETWEEN 78 AND 78.99 THEN 1 ELSE 0 END) AS LvLOff78,
SUM(CASE WHEN ba.LvLOff BETWEEN 79 AND 79.99 THEN 1 ELSE 0 END) AS LvLOff79,
SUM(CASE WHEN ba.LvLOff BETWEEN 80 AND 80.99 THEN 1 ELSE 0 END) AS LvLOff80,
SUM(CASE WHEN ba.LvLOff BETWEEN 81 AND 81.99 THEN 1 ELSE 0 END) AS LvLOff81,
SUM(CASE WHEN ba.LvLOff BETWEEN 82 AND 82.99 THEN 1 ELSE 0 END) AS LvLOff82
FROM relation_bases b
JOIN relation_alliance a ON a.WorldId=b.WorldId
JOIN relation_player p ON p.WorldId=b.WorldId and p.AllianceId=a.AllianceId AND p.AccountId=b.AccountId
JOIN bases ba ON ba.WorldId=b.WorldId AND ba.BaseId=b.BaseId
AND ba.Zeit=(SELECT ba.Zeit FROM bases ba WHERE ba.WorldId=b.WorldId AND ba.BaseId=b.BaseId ORDER BY ba.Zeit DESC LIMIT 1)
WHERE
IF (_WorldId > 0, _WorldId = b.WorldId, true)
AND
IF (_AllianceId > 0, _AllianceId = p.AllianceId, true)
AND
IF
(
	(SELECT _OwnAccountId IN (SELECT l.AccountId FROM login l WHERE l.IsAdmin=true)),
	true,
	(
        (
            b.WorldId IN
			(
				SELECT p2.WorldId FROM relation_player p2 WHERE p2.AccountId=_OwnAccountId
			)
        )
        AND
        (
        	(
				a.AllianceId=
				(
					SELECT p2.AllianceId FROM relation_player p2 WHERE p2.WorldId=b.WorldId AND p2.AccountId=_OwnAccountId
				)
				AND
				IF
				(
					(SELECT p2.MemberRole FROM relation_player p2 WHERE p2.AccountId=_OwnAccountId AND p2.WorldId=b.WorldId)<=a.MemberRole,
					true,
					p.AccountId=_OwnAccountId
				)
			)
			OR
			(
				a.AllianceId=
				(
					SELECT ash.AllianceIdSet FROM relation_alliance_share ash
					JOIN relation_player p2 ON p2.WorldId=ash.WorldId AND p2.AllianceId=ash.AllianceIdGet
					WHERE ash.WorldId=b.WorldId AND p2.AccountId=_OwnAccountId
				)
				AND
				IF
				(
					(SELECT p2.MemberRole FROM relation_player p2
					WHERE p2.WorldId=b.WorldId AND
					p2.AccountId=_OwnAccountId)<=(SELECT ash.MemberRoleAccess FROM relation_alliance_share ash
					JOIN relation_player p2 ON p2.WorldId=ash.WorldId AND p2.AllianceId=ash.AllianceIdGet
					WHERE ash.WorldId=b.WorldId and p2.AccountId=_OwnAccountId),
					true,
					false
				)
			)
			OR
			(
				p.AccountId=
				(
					SELECT psh.AccountIdSet FROM relation_player_share psh
					WHERE psh.WorldId=b.WorldId
					AND psh.AccountIdGet=_OwnAccountId
				)
			)
        )
    )
);